name: CICD
run-name: Script daily execution

on:
    push:
        branches:
            - "main"
            - "master"
    workflow_dispatch:

jobs:
    setup_tag:
        name: Setup tags
        outputs:
            docker_tag: ${{ steps.vars.outputs.sha_short }}
        permissions:
            id-token: write
            contents: read
            actions: read

        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Login action
              uses: docker/login-action@v2
              with:
                  username: __DOCKER_USER__
                  password: __DOCKER_PASSWORD__

            - name: Set and check commit variable
              id: vars
              run: |
                  echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
                  echo ${{ steps.vars.outputs.sha_short }}

    build:
        name: Build and push
        needs: setup_tag
        permissions:
            id-token: write
            contents: read
            actions: read

        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Login action
              uses: docker/login-action@v2
              with:
                  username: __DOCKER_USER__
                  password: __DOCKER_PASSWORD__

            - name: Building
              run: docker build -t ${{ secrets.__DOCKER_USER__ }}/tal:${{ needs.setup_tag.outputs.docker_tag }} -t ${{ secrets.DOCKER_USER}}/tal:latest .

            - name: Pushing SHA tag
              run: docker push ${{ secrets.__DOCKER_USER__ }}/tal:${{ needs.setup_tag.outputs.docker_tag }}

            - name: Pushing latest tag
              run: docker push ${{ secrets.__DOCKER_USER__ }}/tal:latest

    running_app:
        name: Running app
        needs: [build, setup_tag]
        permissions:
            id-token: write
            contents: read
            actions: read

        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Login action
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.__DOCKER_USER__ }}
                  password: ${{ secrets.__DOCKER_PASSWORD__ }}

            - name: Running app
              run: docker run ${{ secrets.__DOCKER_USER__ }}/tal:${{ needs.setup_tag.outputs.docker_tag }}
